apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: teste 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teste 
    spec:
      containers:
        - name: teste 
          image: cniregistry.azurecr.io/teste
          ports:
          - containerPort: 8080